version: '3'
services:
  api:
    build: .
    ports:
      - "5000:5000"
    networks:
      lifeworks:
        aliases:
          - api
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
  worker:
    build: .
    networks:
      lifeworks:
        aliases:
          - worker
    volumes:
      - .:/code
    command: celery worker -B -l info -A api.celery
  redis:
    image: "redis"
    networks:
      lifeworks:
        aliases:
          - redis
  db:
    image: "influxdb"
    ports:
      - "8086:8086"
    networks:
      lifeworks:
        aliases:
          - db
  geoip-api:
    image: "workivate/geoip-api"
    networks:
      lifeworks:
        aliases:
          - geoip-api


networks:
  lifeworks:
    external: true
